Third try (the reference was main, so we need to use another way to get the branch name) (#219)
* Adding action for deleting image

* Only trigger when deleting

* Adding service principal to login to Azure

* Using the wrong tag

* Pulling the correct branch name

* Fixing reference

* Branch name shouldn't be main

* Getting the refenrece right

diff --git a/.github/workflows/delete-container-tag.yaml b/.github/workflows/delete-container-tag.yaml
--- a/.github/workflows/delete-container-tag.yaml
+++ b/.github/workflows/delete-container-tag.yaml
@@ -9,6 +9,7 @@ env:
 
 jobs:
   delete-container:
+    if: github.event.ref_type == 'branch'
     runs-on: cfa-cdcgov
     name: Deleting the container
 
@@ -16,18 +17,14 @@ jobs:
       - name : Checkout code
         uses: actions/checkout@v4
 
-      - name: Extract branch name
-        shell: bash
-        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
-        id: branch-name
-
       - name: Figure out tag (either latest if it is main or the branch name)
         id: image-tag
         run: |
-          if [ "${{ steps.branch-name.outputs.branch }}" = "main" ]; then
-            echo "tag=latest" >> $GITHUB_OUTPUT
+          if [ "${{ github.event.ref }}" = "main" ]; then
+            echo "The image associated with the main branch cannot be deleted."
+            exit 1
           else
-            echo "tag=${{ steps.branch-name.outputs.branch }}" >> $GITHUB_OUTPUT
+            echo "tag=${{ github.event.ref }}" >> $GITHUB_OUTPUT
           fi
 
       - name: Login to the Container Registry
@@ -37,7 +34,7 @@ jobs:
           username: "cfaprdbatchcr"
           password: ${{ secrets.CFAPRDBATCHCR_REGISTRY_PASSWORD }}
 
-      - name: Login to Azure with STF Service Principal
+      - name: Login to Azure with NNH Service Principal
         id: azure_login_2
         uses: azure/login@v2
         with:
