adding build args, using OIDC, updating Makefile

diff --git a/.github/workflows/delete-container-tag.yaml b/.github/workflows/delete-container-tag.yaml
--- a/.github/workflows/delete-container-tag.yaml
+++ b/.github/workflows/delete-container-tag.yaml
@@ -8,6 +8,11 @@ env:
 
 jobs:
   delete-container:
+    permissions:
+      contents: read
+      id-token: write
+      packages: read
+    environment: production
     if: github.event.ref_type == 'branch'
     runs-on: ubuntu-latest
     name: Delete tag
@@ -26,6 +31,18 @@ jobs:
             echo "tag=${{ github.event.ref }}" >> $GITHUB_OUTPUT
           fi
 
+      # From: https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#requesting-the-jwt-using-the-actions-core-toolkit
+      - name: Install OIDC Client from Core Package
+        run: npm install @actions/core@1.6.0 @actions/http-client
+      - name: Get Id Token
+        uses: actions/github-script@v7
+        id: idtoken
+        with:
+          script: |
+            const coredemo = require('@actions/core')
+            const id_token = await coredemo.getIDToken('api://AzureADTokenExchange')
+            coredemo.setOutput('id_token', id_token)
+
       - name: ACR Import
         uses: CDCgov/cfa-actions/runner-action@v1.3.0
         with:
@@ -34,19 +51,19 @@ jobs:
           wait_for_completion: true
           print_logs: true
           script: |
+            echo "Logging into Azure CLI"
             az login --service-principal \
             --username ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).clientId }} \
-            --password ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).clientSecret }} \
-            --tenant ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).tenantId }}
+            --tenant ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).tenantId }} \
+            --federated-token ${{ steps.idtoken.outputs.id_token }} \
+            --output none
 
-            # Remove the image from the registry
+            echo "Remove the image from the registry"
             az acr repository delete \
               --yes \
               --name ${{ vars.CONTAINER_REGISTRY_NAME }} \
-              --image ${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}
+              --image ${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }} && echo "Deleted image tag!"
 
-            # Remove the dependencies image from the registry
-            az acr repository delete \
-              --yes \
-              --name ${{ vars.CONTAINER_REGISTRY_NAME }} \
-              --image ${{ env.IMAGE_NAME }}:dependencies-${{ steps.image-tag.outputs.tag }}
+            if [ $? -ne 0 ]; then
+              echo "Failed to delete image tag"
+            fi
